### ISSUE TITLE
[BUG] : 로그인 에러

### ISSUE THREAD

**Issue by devgoodway** [bmrdevteam/school-information-system#23]
**Description**
bmrAdmin 로그인 시도시 발생

**Reproduce**

버그 발생 경로를 적어주세요:
1.  로그인 화면에서 별무리학교 아카데미를 선택후 bmrAdmin 계정으로 로그인을 시도하면 blank 화면이 출력되면서 에러 발생

**사용환경**
OS: macOS Ventura 13.0(22A380)
BROWSER: Chrome

**스크린샷**
![image](https://user-images.githubusercontent.com/22511259/210189678-96e7702b-7fd7-4e5a-8ae7-13198038483f.png)

**기타 사항**

**Comment by jessie129j** [comment]
해결했습니다
