### ISSUE TITLE
[BUG] : 학기의 활성화와 비활성화에서 오류가 발생합니다.

### ISSUE THREAD

**Issue by devgoodway** [bmrdevteam/school-information-system#24]
**Description**
신규 학교에서 활성화되어있는 학기를 비활성화하거나 비활성화되어있는 것을 활성화하려고 하면 오류가 발생함.

**Reproduce**
버그 발생 경로를 적어주세요:
1.  별무리 초중등학교 > 학교관리 > 학기 > 활성화 or 비활성화
2. undefined 에러 발생

**사용환경**
OS: macOS Ventura 13.0(22A380)
BROWSER: Chrome

**스크린샷**
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/22511259/210309021-dc6511ee-4563-4354-b79f-7f63d24ab029.png">
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/22511259/210309152-f954194c-b2f7-4858-8974-9275cb107299.png">

**기타 사항**

**Comment by jessie129j** [comment]
저는 잘 되는데 dev 최신으로 받아서 다시 확인해주시겠어요?

![Screenshot 2023-01-04 at 11 55 45](https://user-images.githubusercontent.com/19641212/210475993-834477a8-f0f2-44aa-8cd4-741180b44e71.JPG)
![Screenshot 2023-01-04 at 11 56 08](https://user-images.githubusercontent.com/19641212/210475996-9aacd1bb-93f7-49b6-ba8d-c1a10255a1b9.JPG)

**Comment by devgoodway** [comment]
이것도 yarn package 재설치 문제였네요;;
