### ISSUE TITLE
[BUG] : 강의실 추가 기능에서 발생하는 오류

### ISSUE THREAD

**Issue by devgoodway** [bmrdevteam/school-information-system#26]
**Description**
강의실 추가 기능에서 발생하는 오류

**Reproduce**

버그 발생 경로를 적어주세요:
1. 관리자 > 학교관리 > 강의실에서 추가 및 삭제를 실행하면 blank화면과 함께 로그아웃되는 문제가 발생
**사용환경**
OS: mac
BROWSER: Chrome

**스크린샷**
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/22511259/210317651-55a2e5c3-6e66-48d8-b70d-bd4575102f27.png">
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/22511259/210317789-1741c1fe-8c9d-425c-b1cd-96969b90db46.png">

**기타 사항**

**Comment by seedlessapple** [comment]
![Screenshot 2023-01-04 at 01 25 13](https://user-images.githubusercontent.com/102509219/210398440-50ddcba8-4a93-4f38-8384-204adc47fb0e.png)

**Comment by devgoodway** [comment]
여전히 문제가 발생 중인데 아래 에러 코드도 확인 부탁해요.

![image](https://user-images.githubusercontent.com/22511259/210462856-ae0842fd-39a3-4b39-ae79-7d14357ba9a5.png)

**Comment by jessie129j** [comment]
동일한 계정으로 로그인했는데 저는 잘 작동합니다...

![Screenshot 2023-01-04 at 12 06 57](https://user-images.githubusercontent.com/19641212/210477227-dd30bdd5-a9ca-41d1-a5ac-0e35945cbdef.JPG)

**Comment by devgoodway** [comment]
yarn package 설치를 다시 했더니 정상작동하네요!
