### ISSUE TITLE
[FEATURE]: 선택된 사용자 학교 설정 제안

### ISSUE THREAD

**Issue by devgoodway** [bmrdevteam/school-information-system#30]
**Description**
선택된 사용자의 등록된 학교를 미리 체크해주면 좋을 것 같습니다.

![image](https://user-images.githubusercontent.com/22511259/210472497-d20c1107-0b71-4866-a4b5-f858e68d2d29.png)

**Comment by jessie129j** [comment]
@seedlessapple 특정 체크박스를 체크해놓은 상태로 테이블을 생성할 수 있나요?

**Comment by seedlessapple** [comment]
테이블에 들어가는 데이터에 tableRowChecked = True 하시면 될거에요

**Comment by devgoodway** [comment]
일괄 설정은 그대로 유지
