### ISSUE TITLE
[BUG] : 사용자 선택된 유저 삭제 (임시) 동작하지 않음

### ISSUE THREAD

**Issue by devgoodway** [bmrdevteam/school-information-system#32]
**Description**
사용자 선택된 유저 삭제 기능 동작하지 않음

**Reproduce**

버그 발생 경로를 적어주세요:
1. 관리자 > 학교관리 > 자세히 > 학기 > 자세히 > 사용자 선택된 유저 삭제 (임시)
2. 새로고침을 한뒤
3. 회원가입 버튼 클릭시 - 404 에러 발생

**사용환경**
USER : bmrAdmin
URL : http://localhost:3030/admin/schools/63a41349c9930982934900c8#%ED%95%99%EA%B8%B0
OS: Mac
BROWSER: Chrome

**스크린샷**
![image](https://user-images.githubusercontent.com/22511259/210473830-832b7062-a8a0-42c1-840e-c963e5ff53fe.png)

**기타 사항**
❗ 구현이 안된 것이라면 구현이 필요함

**Comment by jessie129j** [comment]
지금도 안되나요?

**Comment by devgoodway** [comment]
잘 동작합니다! `(임시)`는 지워도 될 것 같아요
