### ISSUE TITLE
[FEATURE]: 관리자 기능 수정 제안(학교 관리 메뉴, 양식과 권한 탭)

### ISSUE THREAD

**Issue by devgoodway** [bmrdevteam/school-information-system#35]
### **Description**
**가) 학교 관리 메뉴 구성 수정**
- 학교 관리 메뉴가 해당 학기의 정보를 수정하지 않으면서 같은 메뉴에 배치됨으로 인해 혼란스러움이 있어 아래와 같이 수정하는 것을 제안합니다. 

1. 학교 관리 메뉴 탭 
- 기존 [기본 정보 / 학기 / 사용자 / 교과목 / 강의실 / 양식 / 권한 / 기록 관리]를 [학기 / 기록]으로 수정

2. 학기 추가 방식 변경
- [+ 새로운 학기 추가] 버튼 클릭 시 [학기>자세히] 버튼 클릭 시 보이는 화면과 같은 화면에서 생성 할 수 있도록 단일화 한다. 
* 기존 수정 화면에서 학년도와 학기를 넣는 필드를 추가 하는 방식
- 이전에 생성된 학기 정보를 복사하여 생성하는 기능을 구현하여 default 값 대체
![image](https://user-images.githubusercontent.com/22511259/210674981-5bf1f697-2cf4-44cd-965a-3225b21fc367.png)
![image](https://user-images.githubusercontent.com/22511259/210675284-2b18ac32-615c-4491-970a-8b6126b0c396.png)

**나) 양식과 권한 탭 화면 구성 수정**
- 탭을 확인 했을 때 등록된 세부 내용을 확인 할 수 없는 불편함이 있어 아래와 같이 수정하는 것을 제안합니다.
1) 양식 탭 수정
- 기존 [시간표 양식 / 강의 계획서 양식 / 평가 양식] 하단에 버튼을 배치하는 방식에서 테이블 형태로 구현하는 것을 제안합니다.
![image](https://user-images.githubusercontent.com/22511259/210676305-016dbbd0-126b-49c2-a404-cdf9564b4c0c.png)
![image](https://user-images.githubusercontent.com/22511259/210678225-97157f2c-4982-461e-8119-61e0c3fd1ac5.png)
2) 권한 탭 수정
- 기존 [수업 개설 권한 / 수강 신청 권한 / 평가 권한] 하단에 버튼을 배치하는 방식에서 테이블 형태로 구현하는 것을 제안합니다.
![image](https://user-images.githubusercontent.com/22511259/210676853-a50309dc-1ce9-4c73-992c-491676d09846.png)
![image](https://user-images.githubusercontent.com/22511259/210678278-c6798cc9-c776-433b-a50d-45bcb2988e0e.png)

**Comment by jessie129j** [comment]
질문이 있습니다

가)
1. 학교 관리 메뉴 탭을 [학기/기록]으로 수정하면 사용자(학교에 등록된 사용자 확인), 교과목, 강의실, 양식, 권한은 어디서 확인하나요?
2. 사용자가 복사할 학기를 선택하면 그 학기의 값이 복사되고 선택하지 않으면 학교의 값이 복사되는건가요?

**Comment by devgoodway** [comment]
> 질문있습니다!
> 
> 
> 
> 가)
> 
> 1. 학교 관리 메뉴 탭을 [학기/기록]으로 수정하면 사용자(학교에 등록된 사용자 확인), 교과목, 강의실, 양식, 권한은 어디서 확인하나요?
해당 학기에 세부 항목에서 확인합니다.
> 
> 2. 사용자가 복사할 학기를 선택하면 그 학기의 값이 복사되고 선택하지 않으면 학교의 값이 복사되는건가요?
복사를 선택하지 않으면 비어있는 양식으로 등록을 시작합니다.
> 
>

**Comment by jessie129j** [comment]
학교 도큐먼트에서 교과목/강의실/양식/권한을 설정하고 새로운 학기를 생성할 때 해당 값을 복사하는 방식을 아예 없애자는 말씀이신가요?

**Comment by jessie129j** [comment]
+
학교 도큐먼트의 교과목/강의실/양식/권한과 학기 도큐먼트의 교과목/강의실/양식/권한은 별개인데 학교 도큐먼트의 교과목/강의실/양식/권한을 없애자는 말씀이신가요?

**Comment by devgoodway** [comment]
> 학교 도큐먼트의 교과목/강의실/양식/권한과 학기 도큐먼트의 교과목/강의실/양식/권한은 별개인데 학교 도큐먼트의 교과목/강의실/양식/권한을 없애자는 말씀이신가요?

그게 맞아. 학교 도큐먼트를 유지하는게 불필요하다는 생각이 드는데 의견은 어떠신지?

**Comment by jessie129j** [comment]
> > 학교 도큐먼트의 교과목/강의실/양식/권한과 학기 도큐먼트의 교과목/강의실/양식/권한은 별개인데 학교 도큐먼트의 교과목/강의실/양식/권한을 없애자는 말씀이신가요?
> 
> 그게 맞아. 학교 도큐먼트는 학기를 생성하기 위한 디폴트 값을 가지는 의미만 있는 것 같아 그래서 학교 도큐먼트를 유지하는게 불필요하다는 생각이 드는데 의견은 어떠신지?

저도 그게 더 좋을 것 같네요.
@seedlessapple 어떻게 생각하시나요?

**Comment by jessie129j** [comment]
**가) 학교 관리 메뉴 구성 수정**

**1. 학교 관리 메뉴 탭**
기존 탭 [기본 정보 / 학기 / 사용자 / 교과목 / 강의실 / 양식 / 권한 / 기록 관리]을 [학기 / 기록 / 사용자] 로 수정함
사용자 탭에서는 학교에 가입된 사용자 목록과 사용자의 시즌 등록 정보를 확인할 수 있는데 필요할 것 같아서 일단 남겨두었습니다

**2. 학기 추가 방식 변경**
[+새로운 학기 추가] 버튼 클릭 시 학년도(필수), 학기(필수), period, 복사할 학기를 선택하여 시즌을 먼저 생성한 후 [학기>자세히]창으로 넘어가도록 구현했습니다.
![season_1](https://user-images.githubusercontent.com/19641212/211243572-4cf0fa91-b482-4c7b-a66a-dcc1dbbb9349.png)
![season_2](https://user-images.githubusercontent.com/19641212/211243577-57a78f00-71eb-42d6-b2d1-a3834149452b.png)


**나) 양식과 권한 탭 화면 구성 수정**

**1. 양식 탭을 다음과 같이 수정했습니다.**
![season_5](https://user-images.githubusercontent.com/19641212/211243584-cce43f7a-15ba-4e37-900d-dcf5142f3c2e.png)

**2. 권한 탭을 다음과 같이 수정했습니다.**
![season_6](https://user-images.githubusercontent.com/19641212/211243588-98c986d4-6de3-4ecd-9845-4083b57db277.png)

**기타) 사용자 탭 화면 수정**
![season_3](https://user-images.githubusercontent.com/19641212/211243579-d76b2640-323d-4956-8e8a-f52e2dba36cd.png)
![season_4](https://user-images.githubusercontent.com/19641212/211243582-a866686e-ec74-45b4-8c7d-f61ded0e926e.png)

**Comment by devgoodway** [comment]
수고했어요!! 사용하기 좋도록 잘 만들어 진 것 같아요!!

테스트를 하고 있는데 몇가지 발생하는 오류가 있는데 확인 부탁해요!

1. 메니저 권한에서 학기 리스트가 출력되지 않음.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/22511259/211257280-c5d18610-7d65-4bb3-8477-bfa396f0131d.png">
- 학기를 추가한 이후에는 리스트가 출력되는데 확인 필요

2. 교과목 헤더와 항목 등록 오류 발생
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/22511259/211257668-503ae064-1033-41b7-baa3-096c829d6899.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/22511259/211257742-dbdd8bbf-cafa-462c-925c-b99216f21453.png">

3. 강의실 등록시 오류 메세지 출력 후 등록
![image](https://user-images.githubusercontent.com/22511259/211257794-de3cd676-c8cf-46ad-9236-12ef72634565.png)

**Comment by jessie129j** [comment]
저한테는 해당 에러가 발견되지 않아서 오류 메시지를 조금 다르게 출력하도록 수정했습니다. 
오류 발생하는 스크린샷 다시 찍어주시면 확인해보겠습니다!

**Comment by devgoodway** [comment]
> 저한테는 해당 에러가 발견되지 않아서 오류 메시지를 조금 다르게 출력하도록 수정했습니다. 
> 
> 오류 발생하는 스크린샷 다시 찍어주시면 확인해보겠습니다!

네 다시 확인 해보고 답글 달께요

**Comment by devgoodway** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/22511259/212067840-5853d145-8813-4373-9bb1-e88938c01246.png">

팝업에는 뜨지 않고 콘솔에만 찍힙니다!

**Comment by jessie129j** [comment]
reference:
https://www.mongodb.com/community/forums/t/mongoose-version-error-no-matching-document-found-for-id/134781/4

mongoose는 도큐먼트의 버전을 관리하면서 서로 다른 두 어플리케이션이 동시에 하나의 도큐먼트를 수정할 때 해당 에러를 발생시키는데 이 문제는 브라우저가 동일한 요청을 빠르게 두 번 보내서 생기는 문제 같아요
특정 브라우저 또는 브라우저 설정 값에 따라 이렇게 되는게 아닐까... 추측해봅니다

1. 첫 번째 요청을 보내면 v.0의 season 도큐먼트를 찾아서 수정하고
2. 바로 동일한 두 번째 요청이 오면 v.0의 season 도큐먼트를 찾아서 수정하고
3. 1번이 완료되면 season 도큐먼트를 저장하고 리턴합니다. 이 때 도큐먼트가 v.1로 버전이 올라가요. 
4. 2번이 완료되고 season 도큐먼트를 저장하려 할 때 v.0 도큐먼트가 더이상 존재하지 않기 때문에 'no matching document...' 에러를 리턴합니다.

그래서 3번의 결과로 success 팝업이 뜨고 4번의 결과로 에러가 뜨는 것 같습니다

일단 mongoose에서 다른 함수를 적용해봤는데 재확인 부탁드려요!

**Comment by devgoodway** [comment]
> reference: https://www.mongodb.com/community/forums/t/mongoose-version-error-no-matching-document-found-for-id/134781/4
> 
> mongoose는 도큐먼트의 버전을 관리하면서 서로 다른 두 어플리케이션이 동시에 하나의 도큐먼트를 수정할 때 해당 에러를 발생시키는데 이 문제는 브라우저가 동일한 요청을 빠르게 두 번 보내서 생기는 문제 같아요 특정 브라우저 또는 브라우저 설정 값에 따라 이렇게 되는게 아닐까... 추측해봅니다
> 
> 1. 첫 번째 요청을 보내면 v.0의 season 도큐먼트를 찾아서 수정하고
> 2. 바로 동일한 두 번째 요청이 오면 v.0의 season 도큐먼트를 찾아서 수정하고
> 3. 1번이 완료되면 season 도큐먼트를 저장하고 리턴합니다. 이 때 도큐먼트가 v.1로 버전이 올라가요.
> 4. 2번이 완료되고 season 도큐먼트를 저장하려 할 때 v.0 도큐먼트가 더이상 존재하지 않기 때문에 'no matching document...' 에러를 리턴합니다.
> 
> 그래서 3번의 결과로 success 팝업이 뜨고 4번의 결과로 에러가 뜨는 것 같습니다
> 
> 일단 mongoose에서 다른 함수를 적용해봤는데 재확인 부탁드려요!

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/22511259/212685190-47992020-d3c2-4450-8ecc-69348be84405.png">

몇가지 테스트를 해보았는데
1. 강의실 등록 테스트
- 처음 등록 시에는 에러가 발생하지 않았지만 두번째 등록시에는 에러 발생
- 다시 로그인 한 이후에 다시 시도했을 때에도 동일한 에러 발생
- 설명 한 것 처럼 요청이 2번 보내지는 상황이 발생하고 있음
2. 교과목 등록 테스트
- 요청이 2번 보내지는 상황이 발생하지만 오류코드는 발생하지 않음

**Comment by jessie129j** [comment]
헉 최신 dev를 pull해도 그런가요?ㅠㅠ

**Comment by devgoodway** [comment]
> 헉 최신 dev를 pull해도 그런가요?ㅠㅠ

ㅠㅠ 최신 dev 였는데 그러네 왜 요청이 2번 보내지는지 모르겠네

**Comment by jessie129j** [comment]
success 메시지도 뜨고 추가된 강의실도 화면에 나타나나요? 그러면 작동은 되는 것이니 실사용 전까지 해결 안되면 에러에 대해 alert나 콘솔 메시지를 출력하지 않도록 하면 될 것 같긴 해요

**Comment by devgoodway** [comment]
> success 메시지도 뜨고 추가된 강의실도 화면에 나타나나요? 그러면 작동은 되는 것이니 실사용 전까지 해결 안되면 에러에 대해 alert나 콘솔 메시지를 출력하지 않도록 하면 될 것 같긴 해요

그래요 일단 그렇게 마무리 합시다!
