### ISSUE TITLE
[FEATURE]: 학기별 양식 수정 권한 관련 제안

### ISSUE THREAD

**Issue by devgoodway** [bmrdevteam/school-information-system#36]
**Description**
### 학기별 양식 수정 권한 관련 제안
학기별로 양식(시간표, 강의 계획서, 평가)를 수정 할 수 있도록 되어있는데 등록과 신청 중에 해당 정보가 수정되면 문제가 발생하게 됩니다. 그래서 해당 학기의 최초 활성화 이후에는 양식을 수정 할 수 없도록 제한하면 좋을 것 같습니다.

**Comment by jessie129j** [comment]
스샷 첨부해서 다시 오픈합니다. 확인하시고 닫아주세요!
![처음활성화)1](https://user-images.githubusercontent.com/19641212/212674150-8b067495-c908-4bdb-bb58-482feab05aae.png)
![처음활성화)2](https://user-images.githubusercontent.com/19641212/212674157-cc3fc966-aad0-4917-b482-5ca9c62f021e.png)
![처음활성화)3](https://user-images.githubusercontent.com/19641212/212674159-487f80cd-3a05-4631-ba8a-76cea918ccdf.png)
![처음활성화)4](https://user-images.githubusercontent.com/19641212/212674163-90de4244-3860-49e8-9522-96cd35e661b6.png)

**Comment by devgoodway** [comment]
네 확인했습니다! 👍
