### ISSUE TITLE
[BUG] : 학기 삭제 후 같은 학기에 수강 신청시 수강 정보 중복 문제

### ISSUE THREAD

**Issue by devgoodway** [bmrdevteam/school-information-system#37]
**Description**
### 학기 삭제 후 같은 학기에 수강 신청시 수강 정보 중복 문제

2023학년도 1쿼터에서 수강 신청 정보를 작성한 이후에 해당 학기를 삭제하고 같은 이름으로 학기를 개설하여 다시 수강 신청을 시도하였더니 강의실 중복 메세지가 뜨면서 문제가 발생하였습니다.

해결 방법은 몇가지가 있을 것 같은데
1. 삭제시 수강 관련 정보까지 삭제한다.
- 실수 등의 이유로 삭제 하였을 때 복구에 어려움이 있다.
`지금과 같이 데이터가 있는 경우 DB에 접속하여 내용을 확인하여 일부 복구 할 수 있다.`

2. 같은 학기 이름으로 생성하지 못하도록 한다.
- 수강 정보(시간표, 강의계획서, 평가)의 수정 때문에 삭제한 경우 의도대로 작업을 진행 할 수 없다.

3. 기존에 저장되어있는 수강 정보들이 기술적으로 인식되지 않도록 처리한다.
- year와 term이 아닌 season ObjectId를 활용해서 처리하도록 작업을 할 수 있다.
- enrollments와 syllabuses에 해당 정보에 대한 작업을 해야한다.

1번과 3번 중에서 해결 방법을 찾으면 좋을 것 같은데 어떻게 하면 좋을까요?

**Reproduce**
버그 발생 경로를 적어주세요:
1. 별무리초중등학교 2023학년도 1쿼터 생성 후 수업 개설 및 수강 신청(리엑트 수업)
2. 별무리초중등학교 2023학년도 1쿼터 삭제
3. 별무리초중등학교 2023학년도 1쿼터 다시 생성
4. 별무리초중등학교 2023학년도 1쿼터에서 같은 강의실 같은 시간에 수업 개설 시도
5. classroom(101호) is not available on 월3,월4 발생

**사용환경**
USER : mrgoodway
URL : http://localhost:3030/courses/design
OS: mac
BROWSER: Chrome

**스크린샷**
![image](https://user-images.githubusercontent.com/22511259/210725399-23c29912-b183-4834-b399-5a43494af986.png)
![image](https://user-images.githubusercontent.com/22511259/210727835-ce039fd9-39ba-4e66-97aa-fead444f9f73.png)

**기타 사항**

**Comment by jessie129j** [comment]
3번으로 해결하면 될 것 같아요!
내일쯤 해보겠습니다
