### ISSUE TITLE
[BUG] : 사이드바 관련 오류

### ISSUE THREAD

**Issue by devgoodway** [bmrdevteam/school-information-system#38]
**Description**
사이드바에서 기능적인 문제를 보이는 것을 확인해보았습니다.

**스크린샷**
**PC**
1. 사이드바 확장시 상하 스크롤 불가 & 상위 메뉴 클릭시 하위 메뉴 축소 확장 불가
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/22511259/210791602-7035a05b-c678-4d83-9f70-8237a6143226.png">

**모바일**
1. 모바일 화면에서 좌측 상단 메뉴 버튼 이미지 분리 : 상단바는 올라가는데 버튼이 고정되어서 발생하는 문제
<img width="638" alt="image" src="https://user-images.githubusercontent.com/22511259/210791273-a0c70f37-d319-408b-856d-274cfe768699.png">

2. 메뉴 클릭시 화면 전환 오류 : 메뉴가 축소되지 않고 화면이 전환 되지 않는 문제
<img width="375" alt="image" src="https://user-images.githubusercontent.com/22511259/210805604-4a54d15a-2048-416f-93b9-6c60bba8e2df.png">

3. 모바일 화면에서 메뉴 버튼 출력 오류 : 메뉴에 접근 할 수 있는 버튼이 출력되지 않는 문제
![IMG_4877](https://user-images.githubusercontent.com/22511259/210805000-7d4fb019-1fa5-470b-973b-204692079c49.PNG)
Safari
![IMG_4876](https://user-images.githubusercontent.com/22511259/210805040-62363113-a99a-478f-b445-211185993105.PNG)
Chrome

**기타 사항**

**Comment by jessie129j** [comment]
@seedlessapple 캘린더에서 스크롤을 내릴 때 scroll chaining 문제가 발생하는 것 같습니다.
현재 다른 페이지에서는 상단바가 제대로 보이지만 캘린더가 포함된 페이지(Home, QuickSearch 결과화면)에서는 스크롤을 올려야 상단바가 보입니다.
QuickSearch 결과화면에서 캘린더 부분만 스크롤되고 전체 화면이 스크롤되는걸 막아주시면 해결될 것 같습니다.
