### ISSUE TITLE
[FEATURE]: 관리자 기능 중 저장 프로세스 관련 제안

### ISSUE THREAD

**Issue by devgoodway** [bmrdevteam/school-information-system#40]
**Description**

- 관리자 기능 중 저장 프로세스가 추가 및 삭제 기능을 동작시킨 후에 저장을 해야 반영되는 프로세스로 되어있는데 사용자가 인지하지 못 할 경우 작업한 데이터를 잃어버릴 수 있습니다. 저장 버튼 없이 해당 데이터 변경이 이루어지도록 수정하면 좋겠습니다.

### 평가
![image](https://user-images.githubusercontent.com/22511259/210914143-fff91bb6-309f-44d0-b7d1-373ffcb6f12f.png)

### 기록
![image](https://user-images.githubusercontent.com/22511259/210913031-75172f63-efac-4a91-8967-9f98020ca9ca.png)
![image](https://user-images.githubusercontent.com/22511259/210913088-9ff13365-c233-49d9-84ff-b32de7e6244a.png)

### 권한
![image](https://user-images.githubusercontent.com/22511259/210912684-60ba9b84-4a56-4d99-b596-4ef23be885b9.png)
![image](https://user-images.githubusercontent.com/22511259/210912701-3ef8c995-232b-47ca-b769-1de31de33f7f.png)
![image](https://user-images.githubusercontent.com/22511259/210912720-3960a4b5-4837-4866-b127-3b249e4e1b2e.png)

**Comment by jessie129j** [comment]
평가 양식, 수업 개설 권한, 수강신청 권한, 평가 권한 저장 방식이 다음과 같이 변경되었습니다
![save_1_평가 양식](https://user-images.githubusercontent.com/19641212/212672944-bfdb8f7a-2c82-4a45-b960-202dcbc4425a.png)
![save_1_권한](https://user-images.githubusercontent.com/19641212/212672960-4b0648da-d8d0-4013-b124-bae49b7f7820.png)

기록 부분은 제가 만든 부분이 아니라 남겨두었습니다!

**Comment by devgoodway** [comment]
> 
잘 수정되었네요! 👍 
기록 부분은 세찬이가 확인해주면 좋을 것 같아요~!
