### ISSUE TITLE
[BUG]: 양식 에디터 메뉴 오류 및 메뉴 구성 제안

### ISSUE THREAD

**Issue by devgoodway** [bmrdevteam/school-information-system#44]
**Bug**
1. 텍스트 메뉴가 하단에 계속 출력된다.
2. 체크박스에서는 텍스트 크기 변환이 이루어지지 않는다.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/22511259/211047814-e76c631a-f529-41c8-b046-f8e97b7ae8b8.png">

**Enhancement**
1. 유형별로 사용 할 수 있는 블럭을 지정한다.(사용 할 수 없는 블럭을 배치하지 않기)
2. 블럭은 선택->추가하는 방식에서 버튼을 클릭하면 생성되는 방식으로 전환한다.
3. 속성을 없애고 유형별 메뉴를 만들어 거기에 너비와 삭제 기능을 추가한다.

<img width="791" alt="image" src="https://user-images.githubusercontent.com/22511259/211049013-b8bd6f12-6890-4dd7-bf85-89af18b71f17.png">

**Comment by devgoodway** [comment]
지금 혹시 작업이 완료 된건가요?
수정하면서 변경된 사항이 좀 있는 것 같아서 댓글에 남깁니다.

1. 양식 유형별로 입력 양식을 선택하는 부분 아직 구현 안된 것으로 보입니다.
2. 드롭다운 필드는 어떤 양식에서도 찾을 수 없습니다.
3. 각 블럭에서 너비를 조정하는 옵션이 없습니다.
4. 테이블 내부에 입력셀과 선택셀에는 필수 선택 부분이 없습니다.

**Comment by seedlessapple** [comment]
확인 해보겠습니다
