### ISSUE TITLE
[FEATURE]: 관리자 > 아카데미 사용자 관리 기능 관련 제안

### ISSUE THREAD

**Issue by devgoodway** [bmrdevteam/school-information-system#50]
**Description**
아카데미 사용자를 등록 할 때 학교를 선택한 이후에 사용자를 등록하게 되어있는데 시스템 상 다른 학교에 등록된 사용자를 등록 할 수 없기 때문에 학교를 선택하지 않고 사용자를 등록하고 이후에 학교를 등록 할 수 있으면 좋을 것 같습니다.

제안 사항
1. 학교 선택 항목 제거 및 아카데미 전체 사용자 출력되도록 수정
2. 테이블에 사용자의 학교 정보도 출력 될 수 있도록 수정
3. 소속 학교 추가 및 삭제 시 기 등록된 정보 체크 될 수 있도록 수정

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/22511259/211834024-10b26f0e-c884-4108-a8de-b72feb6d474d.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/22511259/211835194-3bfa5d34-a812-4a17-9831-df5696a719e3.png">

**Comment by jessie129j** [comment]
다음과 같이 수정되었습니다.

![academy-users-1](https://user-images.githubusercontent.com/19641212/213112968-7d437b00-29e4-4034-8175-67efb89a2b29.png)
![academy-users-2](https://user-images.githubusercontent.com/19641212/213112964-bb1dd2ed-a437-4ba6-a4f6-f1d73d929fe7.png)
