### ISSUE TITLE
[FEATURE]: 담임 교사 인원 조정 제안

### ISSUE THREAD

**Issue by devgoodway** [bmrdevteam/school-information-system#51]
**Description**
별무리 중학교는 한 반에 담임이 2명이라 수업처럼 담임 지정도 2명 이상 지정 할 수 있으면 좋을 것 같습니다.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/22511259/211842309-1dcd960f-73e7-41e5-bdea-51700debe0f2.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/22511259/211842470-244bdc27-7c50-4420-b0d4-642d37000b9b.png">

**Comment by jessie129j** [comment]
registration에 등록되는 담임 선생님을 담임 선생님과 부담임 선생님 두 명으로 제한하는건 어떨까요?
담임 선생님을 세 명 이상 등록하는 경우는 거의 없을 것 같고, 위 방법으로 하면 부담임 선생님 필드만 추가하면 돼서 구현도 간단해서요.

**Comment by devgoodway** [comment]
그래요 그렇게 합시다!

**Comment by jessie129j** [comment]
1. 시즌에 사용자 등록 시 등록 정보 함께 등록할 수 있도록 수정했습니다
![subteacher_1](https://user-images.githubusercontent.com/19641212/213103406-b507d97f-51ce-444b-ab5f-8a9508c9c816.png)
2. '부담임' 필드가 추가되었습니다
![subteacher_2](https://user-images.githubusercontent.com/19641212/213103415-e38bc367-cfe2-4619-ac66-8e294dca533b.png)

**Comment by devgoodway** [comment]
발생한 오류 사항입니다.

1. 사용자 등록에서 부담임 교사 탐색이 안됨.
2. 수정 페이지에서 수정 기능 동작하지 않음.

수정 성공 메세지
<img width="1435" alt="스크린샷 2023-01-25 오전 9 55 50" src="https://user-images.githubusercontent.com/22511259/214456073-24e471d9-e566-4079-8683-f9ea700794d3.png">

반영되지 않은 내용
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/22511259/214455845-08c8d284-5dcc-40d0-9d91-8032e1c758d7.png">

사용자 등록 페이지에서 부담임 교사 탐색 안되는 문제
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/22511259/214455947-f057d840-bae3-4160-a28b-b208403a8ca1.png">

**Comment by jessie129j** [comment]
> 발생한 오류 사항입니다.
> 
> 1. 사용자 등록에서 부담임 교사 탐색이 안됨.
> 2. 수정 페이지에서 수정 기능 동작하지 않음.
> 3. 수정 기능은 다른 입력 사항도 수정 안되고 있음. 확인 필요.
> 

머지 중에 API를 호출하는 부분이 누락되었었네요 (해당 커밋: 7cebafe2309324167163b08ba920b5f88be5f441)
2, 3번은 해결되었는데 1번은 오류 확인이 안됩니다.
담임 선생님 목록은 출력되는데 부담임 선생님은 출력되지 않는건가요?

**Comment by devgoodway** [comment]
선택 옵션에 부담임은 교사 리스트가 출력되지 않는 문제가 발생했어요

**Comment by jessie129j** [comment]
목록을 클릭하고 스크롤을 내렸을 때 목록 출력되는지 확인 부탁드립니다!
스크롤 때문이면 팝업 최소 높이를 높여서 해결할 수 있을 것 같습니다

별무리초중등학교 - 2022학년도 1쿼터
![image](https://user-images.githubusercontent.com/19641212/214467438-1c4fc754-67ab-4929-94ea-9b828bd8aa9d.png)

**Comment by devgoodway** [comment]
네 이전에는 스크롤 높이랑 상관없이 리스트에 뜨지 않았는데 지금은 됩니다. 
스크롤 높이도 조금 조정하면 좋겠네요.
