### ISSUE TITLE
[BUG] : 인물 기능 관련 오류

### ISSUE THREAD

**Issue by devgoodway** [bmrdevteam/school-information-system#55]
**Description**
사진 프로필 적용과 컨텐츠 레이아웃 부분에 문제가 있습니다.

**Reproduce**

버그 발생 경로를 적어주세요:
1.  http://localhost:3030/search/mrgoodway#%EC%9D%BC%EC%A0%95

- [x] 사진에 프로필이 적용되지 않습니다.
- [x] 일정과 시간표 부분의 레이아웃 적용에 문제가 있습니다. (박스로 구분되지 않아 컨텐츠 상하 이동에 어려움이 있음.)

**사용환경**
USER : mrgoodway
URL : http://localhost:3030/search/mrgoodway#%EC%9D%BC%EC%A0%95
OS: mac
BROWSER: Chrome

**스크린샷**
일정
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/22511259/212699003-2398a384-edbc-48a5-905b-8315ba225d61.png">
시간표
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/22511259/212699088-52036195-7425-48e7-8682-6feadb2877b4.png">
문서
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/22511259/212699163-fd604ffb-cf50-46ee-86a8-374d83e4411b.png">

**기타 사항**

**Comment by Yeonwu** [comment]
3번 항목은 잘 이해가 되지 않습니다. 제 환경에서 재현도 잘 되지 않네요..
가능하다면 영상으로 찍어서 카톡으로 보내주실 수 있을까요?

**Comment by devgoodway** [comment]
아 컨텐츠 부분이 상단부와 분리 되지 않으면서 어색하게 동작하는 부분을 말하는 것인데 저녁 때 영상으로 찍을 수 있으면 찍어서 보내줄께

**Comment by seedlessapple** [comment]
3번 항목 제가 해결하고 합쳤습니당
