### ISSUE TITLE
[BUG] : 기록 관련 오류

### ISSUE THREAD

**Issue by devgoodway** [bmrdevteam/school-information-system#58]
**Description**
기록을 등록하고 수정하는 기능에 문제가 발생합니다.

**Reproduce**
1. '출결사항'을 기존에 등록했다가 삭제하고 같은 이름으로 다시 등록하려고 하는데 계속 기존 데이터가 출력
- 삭제가 된 것으로 알고 새로 등록하여 진행했으나 실제는 반영되고 있지 않았음.
2. 여러번 시도하다가 삭제가 되었는데 등록이 안되는 문제 발생
3. 이후에는 다른 기록 관련 필드 모두 등록이 안되는 문제가 발생하여 더 이상 진행 할 수 없음

**enhancement**
1. 저장 버튼 없이 추가 삭제가 바로 진행되도록 수정 필요.
2. 선택과 사진 필드 등록 할 수 있도록 수정 필요.
3. 기록 입력 옵션에 그룹별 입력 옵션 추가 필요.

**사용환경**
USER : mrgoodway
URL : http://localhost:3030/admin/schools#%EA%B8%B0%EB%A1%9D%20%EA%B4%80%EB%A6%AC
OS: mac
BROWSER: Chrome

**스크린샷**
저장 프로세스 수정 필요!(작업 몇번 날아갔음ㅠㅠ)
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/22511259/214462660-70f0b00e-f9c6-4bd7-82b3-146e838d16ed.png">

그룹별 입력 옵션 구현
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/22511259/214462742-6c135f63-64fe-4e8d-9d6d-4935914dca3c.png">

**기타 사항**

**Comment by seedlessapple** [comment]
사진은 어떻게 됬나요?? @jessie129j

**Comment by jessie129j** [comment]
별무리 아카데미 > 별무리 고등학교 > 인적 사항에 '사진' 필드가 추가되어 있습니다.
- 사진 필드의 type: 'file-image'
![image](https://user-images.githubusercontent.com/19641212/214601886-9c8134f2-a653-482b-94cc-dc5ef51601ee.png)
![image](https://user-images.githubusercontent.com/19641212/214602907-59f7541d-2bc2-4404-a2de-9db2b6bc98c7.png)

물어보시는게 이거 맞나요?

**Comment by seedlessapple** [comment]
넵

**Comment by devgoodway** [comment]
그룹은 학년, 반, 전체
