### ISSUE TITLE
[BUG] : 기록 입력시 백엔드 서버 다운 발생 오류

### ISSUE THREAD

**Issue by devgoodway** [bmrdevteam/school-information-system#60]
**Description**
기록 필드를 생성하는 작업을 하던 중에 서버가 다운로드 되는 문제가 발생하였습니다.
재시작 이후에는 정상 작동하였으나 원인을 확인 해볼 필요가 있을 것 같습니다.

**Reproduce**

버그 발생 경로를 적어주세요:
1.  관리자>기록 관리에서 '출결사항'등록 이후 확인하는 과정에서 오류 발생
2. 백엔드 서버가 종료 됨

**사용환경**
USER : mrgoodway
URL : http://localhost:3030/admin/schools#%EA%B8%B0%EB%A1%9D%20%EA%B4%80%EB%A6%AC
OS: mac
BROWSER: Chrome

**터미널 에러 메세지**
`
/Users/mrgoodway/Desktop/altsis/school-information-system/backend/node_modules/mongodb/lib/operations/insert.js:53
                return callback(new error_1.MongoServerError(res.writeErrors[0]));
                                ^

MongoServerError: E11000 duplicate key error collection: bmr-db.archives index: school_1_userId_1 dup key: { school: ObjectId('63a41349c9930982934900c8'), userId: "1209" }
    at /Users/mrgoodway/Desktop/altsis/school-information-system/backend/node_modules/mongodb/lib/operations/insert.js:53:33
    at /Users/mrgoodway/Desktop/altsis/school-information-system/backend/node_modules/mongodb/lib/cmap/connection_pool.js:308:25
    at /Users/mrgoodway/Desktop/altsis/school-information-system/backend/node_modules/mongodb/lib/sdam/server.js:213:17
    at handleOperationResult (/Users/mrgoodway/Desktop/altsis/school-information-system/backend/node_modules/mongodb/lib/sdam/server.js:329:20)
    at Connection.onMessage (/Users/mrgoodway/Desktop/altsis/school-information-system/backend/node_modules/mongodb/lib/cmap/connection.js:219:9)
    at MessageStream.<anonymous> (/Users/mrgoodway/Desktop/altsis/school-information-system/backend/node_modules/mongodb/lib/cmap/connection.js:60:60)
    at MessageStream.emit (node:events:513:28)
    at MessageStream.emit (node:domain:489:12)
    at processIncomingData (/Users/mrgoodway/Desktop/altsis/school-information-system/backend/node_modules/mongodb/lib/cmap/message_stream.js:132:20)
    at MessageStream._write (/Users/mrgoodway/Desktop/altsis/school-information-system/backend/node_modules/mongodb/lib/cmap/message_stream.js:33:9) {
  index: 0,
  code: 11000,
  keyPattern: { school: 1, userId: 1 },
  keyValue: {
    school: ObjectId {
      [Symbol(id)]: Buffer(12) [Uint8Array] [
         99, 164,  19,  73, 201,
        147,   9, 130, 147,  73,
          0, 200
      ]
    },
    userId: '1209'
  },
  [Symbol(errorLabels)]: Set(0) {}
}

Node.js v18.12.0
`
**스크린샷**
<img width="898" alt="image" src="https://user-images.githubusercontent.com/22511259/214474127-9ef0d3ff-74d8-43be-83e4-7ce018274efe.png">

**기타 사항**

**Comment by jessie129j** [comment]
1. 해당 에러는 중복키(school, userId) 때문에 발생하는 에러이고, 도큐먼트와 모델에서 인덱스(school, userId)를 삭제했기 때문에 더이상 발생하지 않습니다.

2. 서버 다운을 확인하기 위해 강제로 해당 에러를 발생시켜봤는데, 에러를 리턴하고 서버가 다운되지는 않았었습니다. 서버 다운에는 다른 이유가 있었던 것 같은데 해당 로그로는 확인되지 않습니다. 

3. **archive를 불러오는 과정을 수정했습니다.**
![image](https://user-images.githubusercontent.com/19641212/226383890-506fba14-8aec-4d84-840f-71897510e9ce.png)
-  [기록] 메뉴가 기존 방식이고, [기록2] 메뉴가 새로운 방식입니다.
- 기존 방식은 registration으로 archive를 불러오고(없다면 새로 만들고) 인적사항/출결사항 등 메뉴를 이동할 떄마다 archive.data['인적사항']을 보여줍니다. 이미 로드된 데이터를 불러오기 때문에 그 사이에 다른 사용자가 수정한 것이 반영되지 않습니다.
- 새로운 방식은 registration으로 archive를 불러오고(없다면 새로 만들고) 인적사항/출결사항 등 메뉴를 이동할 때마다 `GET archive/{archive._id}?field='인적사항'` 요청을 보내 최신 데이터를 불러옵니다.

4. @devgoodway [기록2] 메뉴에서 테스트해주시고 에러 나오면 이슈 새로 올려주세요.

**Comment by devgoodway** [comment]
수고했어요! 기록2는 어디서 확인 할 수 있나요? 아카데미나 서버가 다른 것 같아요

**Comment by jessie129j** [comment]
> 수고했어요! 기록2는 어디서 확인 할 수 있나요? 아카데미나 서버가 다른 것 같아요

dev 브랜치에 머지된 상태입니다

**Comment by devgoodway** [comment]
별무리 아카데미에서 확인하는데 확인이 안되네요

**Comment by jessie129j** [comment]
> 별무리 아카데미에서 확인하는데 확인이 안되네요

아 지금은 admin 계정에서만 보이도록 해놨네요. 

1. bmrAdmin으로 로그인
2. bmrAdmin에 학교 + 학기 등록
3. 새로고침
하면 보일텐데 오늘 밤이나 내일중으로 선생님으로 등록된 모든 계정에서 보이도록 해놓을게요.

**Comment by jessie129j** [comment]
@devgoodway 다시 확인해보니 기존의 [기록] 메뉴가 모든 선생님에게 보이지는 않고 [admin, manager] 계정에만 보이는 상태더라구요. [기록2] 메뉴도 [admin, manager] 계정에서만 보이도록 해뒀습니다. 
모든 선생님에게 보이도록 하는건 나중에 하면 될 것 같아요.
