### ISSUE TITLE
[BUG] : 일정 기능 오류

### ISSUE THREAD

**Issue by devgoodway** [bmrdevteam/school-information-system#70]
**Description**
1. 일정을 등록하는 기능이 동작하지 않음
2. 타인의 일정을 등록하는 기능이 표시되어 있음

**스크린샷**
1. 일정을 등록하는 기능이 동작하지 않음
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/22511259/215412913-37f1c76c-33e1-48bd-a9b6-049794703298.png">

2. 타인의 일정을 등록하는 기능이 표시되어 있음
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/22511259/215412954-3976cde5-eb45-4b52-a3bf-f4b28b8e10c4.png">

**기타 사항**

**Comment by Yeonwu** [comment]
여행중이라 내일 확인하겠습니다.

**Comment by jessie129j** [comment]
지금은 userResearchResult페이지에서 다른 사용자가 등록한 일정은 확인할 수 없습니다.
#67 이 PR이 머지되면 수정하겠습니다

**Comment by jessie129j** [comment]
해결되었습니다
