### ISSUE TITLE
[FEATURE]: 수업 개설 - 시간 선택시 세부정보 가져오기

### ISSUE THREAD

**Issue by jessie129j** [bmrdevteam/school-information-system#73]
**Description**
![image](https://user-images.githubusercontent.com/19641212/215633711-2c78672a-fa9a-40f4-a350-b512bf9a5e8a.png)
지금은 이렇게 선택했을 때 `['화2', '화3']`만 가져오는데 이렇게 되면 수강신청을 했을 떄 '일정'페이지에서 보여지지 않습니다.
`[ {label: '화2', day: '화', start: '09:45', end:'10:30'}, {label: '화3', day: '화', start: '10:35', end:'11:20'} ]`
이렇게 가져오면 될것같습니다!

**Comment by jessie129j** [comment]
@seedlessapple  혹시 진행중이신가요...?

**Comment by devgoodway** [comment]
셀을 합쳤을 경우 시간범위를 어떻게 가지고 오나요?
변경된 시간표에는 셀을 합친 것과 합치지 않은 것이 하나의 열에 들어가 있는데 이 경우는 사용 할 수 없는 건가요?
수요일만 2교시가 있고 나머지 월,화,목,금은 1,2교시가 블럭 수업으로 운영됩니다.

<img width="656" alt="image" src="https://user-images.githubusercontent.com/22511259/215868564-d1910534-f37c-4b31-a4a9-ccdceeb2a48c.png">

**Comment by seedlessapple** [comment]
일단 지금 되긴하는데, 선생님이 말씀하시는 방법처럼 진행 하려면 셀마다 시간을 정해주는 방식으로 해야하지 않을까 싶습니다. 관리자가 해줘야하는게 많겠지만 위처럼 진행할까요??

**Comment by devgoodway** [comment]
셀마다 지정하는 방식도 좋을 것 같아요
가능하다면 좌측 시간범위값이 기본으로 들어간 상태에서 수정하는 방식이면 더 좋을 것 같아요

**Comment by seedlessapple** [comment]
넵 수정되었습니다

**Comment by jessie129j** [comment]
![image](https://user-images.githubusercontent.com/19641212/215910488-3cc17620-c497-4e77-bf46-60186611fd3a.png)
day도 추가되어야 합니다!

**Comment by seedlessapple** [comment]
추가 됬습니다

**Comment by jessie129j** [comment]
@seedlessapple 이 이슈는 오늘 밤에 해결해야 할 것 같은데 혹시 언제쯤 가능할까요?ㅠㅠ

**Comment by seedlessapple** [comment]
바꿨습니다

**Comment by jessie129j** [comment]
감사합니다!!! 두시간쯤 뒤에 확인 가능해서 그쯤 수정해서 올리겠습니다

**Comment by jessie129j** [comment]
해결되었습니다
