### ISSUE TITLE
[BUG] : 수업 개설 전 최종 확인 사항

### ISSUE THREAD

**Issue by devgoodway** [bmrdevteam/school-information-system#82]
**Description**
수업 개설을 위해서 작업을 하다보니 수업 개설 전에 반드시 해결되어야 하는 문제가 있습니다.
시간표, 강의 계획서 양식, 평가 양식과 관련된 것은 개설 된 이후에 해당 부분을 수정하기 어려울 것 같습니다.

1. 시간표와 일정 연동 : 지금은 시간표가 등록이 되어도 일정과 연동되지 않습니다. 수업 개설 이후에는 시간값을 다시 넣어줄 수 없습니다.
2. 강의계획서 입력 필드 필수 여부 선택(required 지정) : 지금 안되고 있는데 학기 활성화 이후에는 강의계획서를 수정 할 수 없기 때문에 지금 수정이 되어야 합니다.
3. 평가 양식의 유형에 선택 메뉴 : 회의 때는 기억나지 않았는데 평가 입력 유형에 선택 메뉴가 반드시 들어가야 합니다. 평가 옵션을 지정해서 해당 입력 사항만 받아야 합니다.(평가 점수는 지정된 옵션 중에서만 입력하도록 작업해두어야 합니다. A, B, C, D, E) 이 작업도 학기 활성화 이후에는 수정 할 수 없기 때문에 지금 수정이 되어야 합니다.

위 문제로 인해 오늘은 테스트 학기를 열어서 교육만 진행하려고 합니다. 내일부터는 수업 개설을 할 수 있도록 위 사항 확인 부탁합니다!

**Comment by devgoodway** [comment]
오늘 사용자 교육은 진행했습니다. 위 사항들 최종적으로 확인하고 수업 개설 시작해야하는데 언제쯤 가능하게 될까요?

**Comment by jessie129j** [comment]
1번은 제가 3시간쯤 뒤에 해결할 수 있을 것 같습니다

**Comment by seedlessapple** [comment]
2번 해결했습니다

**Comment by devgoodway** [comment]
> 1번은 제가 3시간쯤 뒤에 해결할 수 있을 것 같습니다

시간값은 필드별로 넣도록 수정되나요?
@seedlessapple

**Comment by jessie129j** [comment]
1번 해결했습니다 - 시간 선택해서 강의계획서 작성 후 수강신청하면 일정에 보입니다

**Comment by jessie129j** [comment]
2번에서 required가 되어야 하는게 강의실, 시간 등만 해당하나요 아님 가치분야, 역량분야같이 formSyllabus를 만들면서 설정하는 부분인가요?

**Comment by seedlessapple** [comment]
그 course moreinfo 부분만 해당 됩니다

**Comment by devgoodway** [comment]
3번은 어떻게 해결을 해야할까요?
일단 텍스트 필드로 만들어두고 나중에 선택 옵션으로 수정 할 수 있나요?

**Comment by jessie129j** [comment]
평가 선택 기능 구현하면 db에서 시즌 데이터 직접 수정해서 해결할 수 있습니다

**Comment by devgoodway** [comment]
그러면 일단 지금 구현된 기능으로 학기 생성해서 활성화하고 선생님들께 작업 하실 수 있게 할께요! 
다음주에는 학생들도 수업개설하기 때문에 구현되는대로 수정하면 좋을 것 같습니다

**Comment by seedlessapple** [comment]
3번 유형부분을 누르면 편집할수있게 해두었습니다 (기록도 동일)

<img width="1074" alt="Screenshot 2023-02-01 at 23 57 58" src="https://user-images.githubusercontent.com/102509219/216195750-fd28a920-dee5-4d8f-a966-300ff652720d.png">
<img width="1074" alt="Screenshot 2023-02-01 at 23 58 08" src="https://user-images.githubusercontent.com/102509219/216195763-1c093c27-50ca-4ad1-bec2-8399cecf3525.png">

**Comment by devgoodway** [comment]
> 3번 유형부분을 누르면 편집할수있게 해두었습니다 (기록도 동일)
> 
> <img alt="Screenshot 2023-02-01 at 23 57 58" width="1074" src="https://user-images.githubusercontent.com/102509219/216195750-fd28a920-dee5-4d8f-a966-300ff652720d.png">
> 
> <img alt="Screenshot 2023-02-01 at 23 58 08" width="1074" src="https://user-images.githubusercontent.com/102509219/216195763-1c093c27-50ca-4ad1-bec2-8399cecf3525.png">

수고했어요! 배포해주면 적용해서 반영해서 평가 양식 작업할게요!

**Comment by jessie129j** [comment]
배포했습니다! 
평가 양식/기록양식을 평가 폼과 기록 폼에 반영하는건 빠르면 오늘 늦으면 내일쯤 가능할 것 같아요

**Comment by devgoodway** [comment]
네 수고했어요!

**Comment by jessie129j** [comment]
평가 양식 평가 폼에 반영후 배포했습니다
![image](https://user-images.githubusercontent.com/19641212/216217495-629da27e-83f8-4af4-84da-ddbc5714ac91.png)

**Comment by devgoodway** [comment]
잠시 후 12시에 수업 개설 시작합니다! 😆
